### ISSUE TITLE
Explore using site checker in bedrock for GA testing

### ISSUE THREAD

**Issue by nathan-barrett** [mozmeao/www-site-checker#9]
Copy of [this issue](https://github.com/mozilla/bedrock/issues/11321) in bedrock but basically seeing if `www-site-checker` is the right tool to use for parsing the HTML in mozilla.org to make sure that GA events contain the correct attribution.

**Comment by stevejalim** [comment]
From the linked issue

> Currently, we aren't doing any testing on any of the data that we send to google analytics. Would be nice to have a testing plan to make sure that when we send something to GA, the correct information is being sent and that attribution is consistent throughout bedrock.

So, thinking out loud, to help decide what's a good direction here.

At the moment, `www-site-checker` runs in its own repo, but the plan is to make it a generally usable Github Action that we can call from Bedrock itself and eventually other web properties (eg, project snowball, in theory, etc). As such, it'd be good to keep everything configuration-based. We could introduce new code to check for GA tags on links, of course, but we'd just have to make the values it was checking come from config.

`www-site-checker` also runs on deployed code/live sites, rather than during CI or development. This is because it checks the state of pages that draw content from various sources (CMS, legal-docs repo, etc), rather than only checking content that's hard-coded in the Bedrock repo. So, if the GA checks had to be pre-deployment, this isn't the right fit. If, though, we could handle getting notified about incorrect attributions _after_ deployment, that would fit with this project. (We could maybe target a dev deployment; it wouldn't neccessarily have to be prod)

Question for you @nathan-barrett: how would we know a GA event had the correct attribution? Could we compare something in the rendered HTML with an expected value, or is the GA stuff set up via JS? `www-site-checker` currenlty does pull down the live HTML of any URL, but doesn't execute any JS. We could spin up a headless browser if needed, I expect, but that does add extra complexity.

**Comment by stevejalim** [comment]
@nathan-barrett I think we can close this, yeah, given you've opted for tests that run during CI?
